version: "3.9"

services:
  php-apache:
      build: .
      container_name: php-apache
      depends_on:
        - db
      volumes:
        - ./src:/var/www/html
      ports:
        - 8081:80

  db:
      container_name: db
      image: mariadb
      restart: always
      environment:
        MARIADB_ROOT_PASSWORD: "dwes"
        MARIADB_DATABASE: "dwes"
        MARIADB_USER: "dwes"
        MARIADB_PASSWORD: "dwes"
      volumes:
        - ./mariadbdata:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    restart: always
    ports:
      - 8082:8080
